dist: xenial

language: python

branches:
  except:
    - staging.tmp
    - trying.tmp

cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - python: 3.4
      env:
      - TOXENV=py34
    - python: 3.5
      env:
      - TOXENV=py35
    - python: 3.6
      env:
      - TOXENV=py36
    - python: 3.7
      env:
      - TOXENV=py37
    - python: 3.7
      env:
      - TOXENV=flake8
    - python: 3.7
      env:
      - TOXENV=pylint
    - python: 3.7
      env:
      - TOXENV=docs
    - python: 3.7
      env:
      - TOXENV=doctest
    - python: 3.7
      env:
      - TOXENV=check-manifest
    - python: 3.7
      env:
      - TOXENV=checkreadme

before_install:
  - pip install codecov # for coverage

install:
  - pip install tox

script:
  - tox

after_success:
  - codecov
